# Generated by Django 4.2.11 on 2026-03-08 22:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(help_text='Identificador único do funcionário', max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='ID do Funcionário')),
                ('name', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('is_active', models.BooleanField(default=True, help_text='Funcionário ativo no sistema', verbose_name='Ativo')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='Departamento')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('entry_time', models.TimeField(verbose_name='Horário de Entrada')),
                ('exit_time', models.TimeField(blank=True, null=True, verbose_name='Horário de Saída')),
                ('entry_confidence', models.FloatField(default=0.0, help_text='Score de similaridade do reconhecimento facial na entrada', verbose_name='Confiança da Entrada')),
                ('exit_confidence', models.FloatField(blank=True, help_text='Score de similaridade do reconhecimento facial na saída', null=True, verbose_name='Confiança da Saída')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to='employees.employee', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Registro de Ponto',
                'verbose_name_plural': 'Registros de Ponto',
                'ordering': ['-date', '-entry_time'],
            },
        ),
        migrations.CreateModel(
            name='FaceEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding_data', models.BinaryField(help_text='Embedding facial serializado (numpy array)', verbose_name='Dados do Embedding')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='employees.employee', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Embedding Facial',
                'verbose_name_plural': 'Embeddings Faciais',
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['emp_id'], name='employees_e_emp_id_12b2ae_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['name'], name='employees_e_name_95200c_idx'),
        ),
        migrations.AddIndex(
            model_name='timelog',
            index=models.Index(fields=['date'], name='employees_t_date_879c20_idx'),
        ),
        migrations.AddIndex(
            model_name='timelog',
            index=models.Index(fields=['employee', 'date'], name='employees_t_employe_cf1127_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='timelog',
            unique_together={('employee', 'date')},
        ),
    ]
